name: Deploy Azure Functions

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install -r Backend/requirements.txt  # Correct path to requirements.txt

      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: sammreen  # Ensure this is the exact Function App name
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}  # Reference to the correct secret
          package: 'Backend'  # Path to the code to be deployed
          scm-do-build-during-deployment: true  # Ensures build happens during deployment
